services:

  react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avalfront
    restart: always
    ports:
      - "80:4345"
    networks:
      - frontend-net

networks:
  frontend-net:
    driver: bridge
