import '@/styles/globals.css'

import SubHeader from '@/components/layout/main/header/subHeader/SubHeader';
import Header from '@/components/layout/main/header/header/Header';
import Footer from '@/components/layout/main/header/footer/Footer';

export const metadata = {
  title: 'Aval Card',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body>
        <SubHeader />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
