import Providers from '@/providers/Providers';
import '@/styles/globals.css'
import "swiper/css";
import "swiper/css/navigation";

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body>

            <Providers>
              {children}
            </Providers>

      </body>
    </html>
  );
}
