import '@/styles/globals.css'

import Footer from "@/components/layout/panel/footer/Footer";
import Header from "@/components/layout/panel/header/Header";
import Panel from "@/components/ui/panel/Panel";
import Sidebar from "@/components/layout/panel/sidebar/SideBar";
import { redirect } from "next/navigation";
import { cookies } from "next/headers";

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  const token = cookies().get("token")?.value;

  // اگر توکن وجود نداشت، ریدایرکت کن
  // if (!token) {
  //   redirect("/login");
  // }
  return (
    <html lang="en" dir="rtl">
      <body>
        <div className={`flex items-stretch`}>
          <Sidebar />
          <div className="mr-5 my-5 ml-8 w-full grid" style={{ gridTemplateRows: 'auto 1fr auto' }}>
            <Header />
            <div className=''>
              {children}
            </div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
